language: go

before_script:
  - go build -o max

script:
  - ./max test

matrix:
  include:
  - os: windows
    go: "1.11"
  - os: osx
    go: "1.11"
  - os: linux
    go: "1.11"
  - os: osx
    go: master
  - os: linux
    go: master
