[[constraint]]
  branch = "master"
  name = "github.com/frozzare/go"

[[constraint]]
  name = "github.com/gorhill/cronexpr"
  version = "1.0.0"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  name = "gopkg.in/yaml.v2"
  version = "2.2.1"
